

services:
  frontend:
    build:
      context: ../zus-project-client
      dockerfile: Dockerfile
   # multi-stage that ends on nginx

    container_name: zus-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads:/usr/share/nginx/uploads:ro
      - letsencrypt:/etc/letsencrypt
      - webroot:/var/www/certbot
    command: >
      /bin/sh -c "
      while :; do
        sleep 12h & wait $${!};
        nginx -s reload;
      done &
      nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - letsencrypt:/etc/letsencrypt
      - webroot:/var/www/certbot
    entrypoint: >
      /bin/sh -c "
      trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h & wait $${!};
      done"



  backend:
    build: .
    container_name: zus-backend
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/zusProjectServer?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: zus
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      FILE_UPLOADS_DIR: /app/uploads
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate


  db:
    image: mysql:8.0
    container_name: zus-mysql
    restart: always
    environment:
      MYSQL_DATABASE: zusProjectServer
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - db_backups:/backups
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
    name: zus_mysql_data
  db_backups: {}  
  letsencrypt: {}     # <— definice chyběla
  webroot: {}

